const { chromium } = require('playwright');
const path = require('path');
const fs = require('fs');
(async () => {
 const browser = await chromium.launch({channel:'msedge', headless:true});
 const page = await browser.newPage({viewport:{width:1500,height:1100}});
 await page.addInitScript(()=>localStorage.setItem('jizura.tourDone','1')); page.setDefaultTimeout(20000); 
 const errors=[]; page.on('pageerror',e=>errors.push(e.message));
 console.log('opening'); await page.goto('file:///'+path.resolve('en/index.html').replaceAll('\\','/'),{waitUntil:'domcontentloaded'});
 console.log('loaded'); if(await page.locator('.tour-skip').isVisible()) await page.locator('.tour-skip').click(); await page.locator('#productVideoCaptions').click();
 await page.locator('#captionVideoFile').setInputFiles('dev/fixtures/media/generated/landscape-10s-30fps-av.mp4');
 await page.waitForFunction(()=>J.captionWorkbench.media?.current?.video?.readyState>=2); console.log('video ready');
 await page.locator('#captionStyleTab_video').click();
 const seek=async time=>page.evaluate(time=>new Promise(resolve=>{ const video=J.captionWorkbench.media.current.video; if(video.currentTime===time) return resolve(); video.addEventListener('seeked',()=>resolve(),{once:true}); video.currentTime=time; }),time);
 const edit=()=>page.evaluate(()=>{ const s=J.captionWorkbench.store.project.settings; return s&&s.videoEdit||null; });
 // Every change is one command: no draft, no Apply button.
 if(await page.locator('#captionVideoEditor [data-action="apply"]').count()) throw Error('The Apply button is back');
 await page.locator('#captionVideoEditor summary').filter({hasText:'Exact times'}).click();
 const clips=page.locator('#captionVideoEditor [data-edit="clips"] input');
 await clips.nth(0).fill('0.2'); await clips.nth(0).dispatchEvent('change');
 await clips.nth(1).fill('1.2'); await clips.nth(1).dispatchEvent('change');
 if(JSON.stringify((await edit()).clips)!=='[{"start":0.2,"end":1.2}]') throw Error('Exact times did not apply at once: '+JSON.stringify((await edit()).clips));
 await seek(0.5); await page.locator('[data-action="split"]').click();
 await seek(0.8); await page.locator('[data-action="split"]').click();
 const bar=await page.locator('#captionVideoEditor [data-edit="trim"]').boundingBox(), total=await page.evaluate(()=>J.captionWorkbench.store.project.media.duration);
 await page.mouse.click(bar.x+bar.width*.65/total,bar.y+bar.height/2);   // select the middle section
 await page.locator('[data-action="removeClip"]').click();
 const pieces=(await edit()).clips.map(c=>c.start.toFixed(2)+'-'+c.end.toFixed(2)).join();
 if(pieces!=='0.20-0.50,0.80-1.20') throw Error('Kept pieces were '+pieces);
 await page.locator('#captionVideoEditor .vs-shape').filter({hasText:'1:1'}).click();
 if((await edit()).format!=='square') throw Error('Shape tile did not apply');
 await page.locator('#captionVideoEditor summary').filter({hasText:'Layout'}).click();
 await page.locator('#captionVideoEditor .vs-layout').filter({hasText:'Stacked'}).click();
 await page.locator('[data-edit="source"]').scrollIntoViewIfNeeded();
 const cropBox=await page.locator('[data-edit="source"]').boundingBox();
 await page.mouse.move(cropBox.x+cropBox.width*.1,cropBox.y+cropBox.height*.1); await page.mouse.down();
 await page.mouse.move(cropBox.x+cropBox.width*.55,cropBox.y+cropBox.height*.7); await page.mouse.up();
 await page.locator('#captionVideoEditor summary').filter({hasText:'Text notes'}).click();
 await seek(0.3); await page.locator('[data-action="note"]').click(); await page.locator('[data-action="note"]').click();
 const notes=page.locator('[data-edit="notes"] textarea');
 await notes.nth(0).fill('A simultaneous note'); await notes.nth(0).dispatchEvent('change');
 await notes.nth(1).fill('Another caption'); await notes.nth(1).dispatchEvent('change');
 await page.locator('#captionUndo').click(); await page.locator('#captionRedo').click();
 console.log('exporting'); const result=await page.evaluate(async()=>{
   const ui=J.captionWorkbench; ui.store.execute({type:'add-caption',text:'Main subtitle',start:0,end:3}); const p=ui.store.project;
   if(Math.abs(p.settings.videoEdit.panels[0].source.w-.45)>.02) throw Error('Source crop drag failed');
   const saved=J.loadProject(ui.store.serialize());
   if(saved.settings.videoEdit.notes.length!==2) throw Error('Notes lost in persistence');
   const result=await new J.CaptionVideoExporter().export(ui.media.current.file,p,{});
   const input=new Mediabunny.Input({formats:Mediabunny.ALL_FORMATS,source:new Mediabunny.BlobSource(result.blob)});
   const v=await input.getPrimaryVideoTrack(),a=await input.getPrimaryAudioTrack();
   const output={width:await v.getCodedWidth(),height:await v.getCodedHeight(),duration:await input.computeDuration(),audio:!!a,reported:result.duration,frames:result.frameCount,mode:result.audio.mode};
   input.dispose();
   const bytes=Array.from(new Uint8Array(await result.blob.arrayBuffer()));
   return {output,bytes};
 });
 fs.mkdirSync('dev/www',{recursive:true}); fs.writeFileSync('dev/www/video-edits-trial.mp4',Buffer.from(result.bytes));
 await page.evaluate(()=> { for(const d of document.querySelectorAll('#captionVideoEditor details details')) d.open=false; document.querySelector('#captionVideoEditor').scrollTop=0; document.querySelector('.caption-stage').scrollTop=0; J.captionWorkbench.preview.renderNow(); });
 await page.screenshot({path:'dev/www/video-edits-trial.png',fullPage:true});
 console.log(JSON.stringify({output:result.output,errors}));
 if(errors.length || result.output.width!==1080 || result.output.height!==1080 || !result.output.audio || Math.abs(result.output.duration-.7)>.1) throw Error('Browser regression failed');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
